id: 9242876a-41c4-42f8-96f8-ac92d6025406
title: Settings
data:
  site_name: 'Joshua Blum'
  social:
    -
      name: Twitter
      url: 'https://twitter.com/_joshuablum'
      icon: site/social-icons/twitter.svg
    -
      name: Github
      url: 'https://github.com/joshuablum'
      icon: site/social-icons/github.svg
    -
      name: Codepen
      url: 'https://codepen.io/joshuablum'
      icon: site/social-icons/codepen.svg
    -
      name: Dribbble
      url: 'https://dribbble.com/joshuablum'
      icon: site/social-icons/dribbble.svg
    -
      name: LinkedIn
      url: 'https://www.linkedin.com/in/josblu'
      icon: site/social-icons/linkedin.svg
    -
      name: Email
      url: 'mailto:hey@joshuablum.net'
      icon: site/social-icons/email.svg